### ISSUE TITLE
Protonect libs and src folders missing

### ISSUE THREAD

**Issue by karolsenami** [hanasaan/ofxMultiKinectV2#12]
Hi, I've tried compiling a 1 month old OF 0.9.0 project from your last commit on this addon and I got the error : `error: no such file or directory : [...]/of_v0.9.3_osx_release/addons/ofxMultiKinectV2/libs/protonect/src/command_transaction.cpp`
`error: no input files`

I couldn't find any other way to fix this error that going back to the previous version of your addon (which worked immediately).

**Comment by hanasaan** [comment]
Do you mean you are developing your own project with this addon?
I think your issue is caused because source file of this addon is changed during the commits.
In that case, try to use project generator for updating the project for removing non existing files,
or try to remove and readd this addon by OFXcodeMenu.
https://github.com/openframeworks/OFXcodeMenu

**Comment by karolsenami** [comment]
I cloned my project from Git in a new OF 0.9.0 folder, then cloned your add-on in the addons folder (and all the other necessary addons), then I used Project Generator to update the addons, then I got the error.

[EDIT] I cleaned the Xcode project then used Project Generator to update the addons of the project and it worked.  Thank you.

**Comment by hanasaan** [comment]
That's weird. 
I successfully built the project with newly cloned OF0.9.0 and ofxMultiKinectV2 addons.

Are you using project generator correctly?
Project generator is used to update project, not the addon.
<img width="612" alt="2016-04-30 14 16 00" src="https://cloud.githubusercontent.com/assets/7454329/14934022/243390ac-0ede-11e6-8be5-eee3baaa5a1e.png">

Anyway, that error seems that old files that are removed recently are still in your xcode project.

<img width="266" alt="2016-04-30 14 20 32" src="https://cloud.githubusercontent.com/assets/7454329/14934037/bbc272ee-0ede-11e6-8c21-de4b2e796cf3.png">
This is correct project status which is generated by the project generator.
