### ISSUE TITLE
Don't know where to put opencl.framework

### ISSUE THREAD

**Issue by moebiusfrost** [hanasaan/ofxMultiKinectV2#2]
Hey,

I'm new to openframeworks and I'm slowly finding my way. Now I want to use the Kinect V2 for some projects. Everything is set up. Your example is working but when I want to make my own openframeworks Project and compile it it says 
![error_01](https://cloud.githubusercontent.com/assets/12255509/7635878/012640b2-fa64-11e4-9f37-78089cdb0798.png)
After I read your instructions i saw that it is neccesary to import opencl.framework. Where do I have to put it. I used the following path
![bildschirmfoto 2015-05-14 um 18 08 24](https://cloud.githubusercontent.com/assets/12255509/7635921/3ef96acc-fa64-11e4-9b6c-0ec7c75de47c.png)
Now it compiles but it stops right at the beginning
![bildschirmfoto 2015-05-14 um 18 09 28](https://cloud.githubusercontent.com/assets/12255509/7635999/61a0cd2c-fa64-11e4-92b9-670fac7c39dd.png)

I hope you can help me

Best Regards

**Comment by hanasaan** [comment]
Your issue seems that libturbojpeg.dylib is not properly copied to excutable directory.
To do so, click project and select "Build Phase" tab, and
add "libturbojpeg.dylib", which should be in ofxTurboJpeg, to "Copy Files".

**Comment by moebiusfrost** [comment]
thank you for your fast response. Where exactly do I put libturbojpeg.dylib in?
![bildschirmfoto 2015-05-14 um 19 40 33](https://cloud.githubusercontent.com/assets/12255509/7637857/3202e5a2-fa71-11e4-8f2c-33eb29e75fa1.png)

**Comment by hanasaan** [comment]
Here is my screenshot.
![2015-05-15 2 48 19](https://cloud.githubusercontent.com/assets/7454329/7638019/eba4f654-faac-11e4-8c40-60c7e3258f29.png)

**Comment by moebiusfrost** [comment]
merci, thank you and Danke schön. It is working :)
