### ISSUE TITLE
Convert ofxMultiKinectV2 to videograbber for Facetracker

### ISSUE THREAD

**Issue by moebiusfrost** [hanasaan/ofxMultiKinectV2#3]
I'm currently working with https://github.com/kylemcdonald/ofxFaceTracker and instead of my built in camera of my macboook, I want to use the Kinect V2 (the IR sensors especially). The problem is, that I can't use it the way the videograbber is declared:
https://github.com/kylemcdonald/ofxFaceTracker/issues/95

I also posted this on the page of the Factracker repository because I was not sure where the cause was. So what is the correct syntax?

Hope you guys can help me. TY

Peace

**Comment by hanasaan** [comment]
It seems that ofxMultiKinectV2 couldn't grab the very first frame since it is unstable during starting-up.
Actually this issue should be fixed.
Working around this issue might be insert checking the size before call ofxFaceTracker like:

``` c++
if (kinect0.getColorPixelsRef().getWidth() > 0) {
  // call ofxFaceTracker here
}
```

**Comment by moebiusfrost** [comment]
thank you. The problem is solved :)

Edit: Its only working with the ColorPixelsRef. But i want to use the Infrared camera. How can I fix that problem?
![bildschirmfoto 2015-06-04 um 22 46 46](https://cloud.githubusercontent.com/assets/12255509/7994173/9e0751fc-0b0b-11e5-8010-28f7d15fc243.png)
![bildschirmfoto 2015-06-04 um 22 46 37](https://cloud.githubusercontent.com/assets/12255509/7994176/a31b1610-0b0b-11e5-9e56-8fe4f59441e9.png)

seems still be the problem about the size.

Thanke you for your help

**Comment by moebiusfrost** [comment]
I still could not solve this problem and I have no clue what the problem is. I tried to prevent to initiate the facetracker at the beginning as you said with 

if (kinect0.getColorPixelsRef().getWidth() > 0)

but with kinect0.getIrPixelsRef().getWidth() > 0 

and then starting the tracker it crashes with the error message above. Despite the fact that it clearly not a size of 0 and the size is even bigger than 0.

Is it something with opencv or with the IR shader?

**Comment by hanasaan** [comment]
IR pixels that are provided from libfreenect2 ranges from 0 to 65535.0,  although it should be from 0 to 1. ofxMultiKinectV2 does not do any normalization, so you should manually do the normalization before you call ofxFaceTracker.
Even worse, it seems  that the face tracker can handle unsigned char pixels (i.e. ofPixels) only.
IR pixels is ofFloatPixels. so you need to do normalization and type conversion (maybe) before calling ofxFaceTracker.

Normalization and type conversion are something like.

``` c++
ofPixels ir;
void setup() {
// ...
ir.allocate(512, 424, 1);
// ...
}

void update() {
// ...
for (int i=0; i<ir.size(); ++i) {
  ir[i] = ofClamp(kinect.getIrPixelsRef()[i] / 256.0, 0, 255);
}
// ...
}
```
