### ISSUE TITLE
set max depth

### ISSUE THREAD

**Issue by antimodular** [hanasaan/ofxMultiKinectV2#6]
hi.
great addon. it looks so useful.
in the kinectv2 addon for OS X one can set the max depth distance, which seems to be around 12m.
is that possible with your addon too?
it seems the depth reading in your example code does not go beyond 5 m.

thanks,
stephan.

**Comment by hanasaan** [comment]
Hi. In my example, the distance is restricted in the fragment shader.

``` c++
        float low1 = 500.0;
        float high1 = 5000.0;
```

These are depth boundaries, which means 500mm to 5000mm is effective depth range.
You can modify these values to extract longer distance depth pixels.

**Comment by antimodular** [comment]
thanks.
