### ISSUE TITLE
 Is this error how to solve ?

### ISSUE THREAD

**Issue by murataka9** [hanasaan/ofxMultiKinectV2#8]
please tell me is this error how to solve ?

![2015-12-28 22 59 07](https://cloud.githubusercontent.com/assets/7837164/12019690/f36bc5e4-adb6-11e5-9646-a60490aa1d2f.png)

**Comment by mattfelsen** [comment]
Looks like you might be using ofxTurboJpeg from armadillu? If so, try using satoruhiga's fork which adds a few new methods, including the missing one that you're running into:
https://github.com/satoruhiga/ofxTurboJpeg

**Comment by hanasaan** [comment]
Thanks Matt for answering this issue

**Comment by mattfelsen** [comment]
My pleasure 😊 Also code from satoruhiga's fork and a couple others were merged into armadillu's, so this issue of using the wrong fork shouldn't be a problem anymore
